version: 0.0
os: linux
files:
  - source: /
    destination: /web/ #where to store the artifacts
hooks:
  AfterInstall:
    - location: scripts/mkdir.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /bin/start.sh #start script for the website
      timeout: 300
      runas: root