# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  pre_build:
    commands:
      - echo Pre-build
  build:
    commands:
      - echo Build started on `date`
      - npm install # run npm install to install all dependencies
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - '**/*' #copy all build files to S3 location